"""Run staged Tree-of-Thought requests with a local HuggingFace model.

This mirrors run_tot_ollama.py but loads models through transformers and adds
branch-level Creative Association RAG before drafting each candidate.
"""

from __future__ import annotations

import json
import gc
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from creative_rag import build_association_packet, format_packet_for_prompt, load_kb
from rerank_tot_candidats import derive_judgment_metrics, rerank


ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = ROOT / "data" / "runs"

# Set REQUEST_PATH to a concrete Path to run a specific request file. Leave it as
# None to run the newest timestamped request generated by build_tot_requests.py.
REQUEST_PATH: Optional[Path] = None

GENERATION_MODEL_ID = "meta-llama/Meta-Llama-3.1-8B-Instruct"
JUDGE_MODEL_ID = "Qwen/Qwen2.5-14B-Instruct"

# Default path: let transformers/accelerate place the model on available GPU(s).
# Set DEVICE_MAP = None to use explicit model.to(DEVICE) instead.
DEVICE_MAP = "auto"
DEVICE = "cuda"
TORCH_DTYPE = "auto"
MAX_NEW_TOKENS = 4096
JUDGE_MAX_NEW_TOKENS = 1024
TEMPERATURE = 0.7
JUDGE_TEMPERATURE = 0.0
CANDIDATE_RETRIES = 2
MIN_CANDIDATE_CHARS = 600
FINAL_REVISION_RETRIES = 1
MIN_FINAL_CANDIDATE_RATIO = 0.7

RAG_MODE = os.environ.get("RAG_MODE", "creative_association")
RAG_TOP_K = int(os.environ.get("RAG_TOP_K", "2"))

# Keep only one HF model in memory at a time. This is slower because the runner
# reloads models when switching between generation and judging, but it avoids
# OOM on a 32GB GPU when using an 8B generator plus a 14B judge.
MEMORY_POLICY = "single_model"


class ProgressBar:
    def __init__(self, total: int, label: str) -> None:
        self.total = max(1, total)
        self.label = label
        self.current = 0

    def update(self, message: str) -> None:
        self.current += 1
        width = 28
        filled = int(width * self.current / self.total)
        bar = "#" * filled + "-" * (width - filled)
        percent = int(100 * self.current / self.total)
        print(
            f"[{bar}] {self.current:>2}/{self.total:<2} {percent:>3}% "
            f"{self.label}: {message}",
            flush=True,
        )


DRAFT_FORMAT_INSTRUCTIONS = """

Draft output contract:
Return exactly one valid JSON object with these top-level keys only:
{
  "branch_id": "same id as the branch plan",
  "candidate_answer": "a complete, directly usable answer as one plain string",
  "self_check_notes": ["short note about constraints covered and association transformed"]
}
Do not put outline headings or act numbers as JSON keys. Put the whole answer,
including headings and bullets if useful, inside candidate_answer as text.
The JSON must be valid: escape line breaks inside candidate_answer as needed; do
not emit an unterminated string or raw multiline JSON string.
If candidate_answer contains paragraphs, encode paragraph breaks as \\n inside
the JSON string.
The candidate_answer must be complete enough for judging, not a stub.
"""

FINAL_REVISION_FORMAT_INSTRUCTIONS = """

Final revision output contract:
The final_answer must contain a complete revised plot design, not just a title.
It must be at least as detailed as selected_candidate.candidate_answer.
Do not shorten the selected candidate.
Do not output only the title.
Do not merely list suggestions.
Apply the selected judgment feedback directly inside final_answer.
revision_notes must describe edits actually made.
"""

ASSOCIATION_JUDGE_INSTRUCTIONS = """

Association-use judging addendum:
The candidate may have received a retrieval packet. Add this exact top-level key
to the judgment JSON:
{
  "association_use": {
    "score_1_to_5": 0,
    "used_item_ids": ["..."],
    "evidence": "...",
    "main_issue": "..."
  }
}
Score 1 means the association is absent, irrelevant, or pasted as exposition.
Score 3 means it is used coherently but shallowly.
Score 5 means it is naturally transformed into plot, character, setting,
imagery, or emotional structure without weakening the original task constraints.
If RAG mode is "none", set score_1_to_5 to 0 and used_item_ids to [].
"""


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as fh:
        for line_no, raw in enumerate(fh, 1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                records.append(json.loads(raw))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {line_no} of {path}") from exc
    return records


def extract_json(text: str) -> Any:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    fenced = re.search(r"```(?:json)?\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    if fenced:
        return json.loads(fenced.group(1).strip())

    match = re.search(r"(\{.*\}|\[.*\])", text, flags=re.DOTALL)
    if not match:
        raise ValueError(f"Model did not return JSON: {text[:500]}")
    return json.loads(match.group(1))


class HFChatClient:
    def __init__(self) -> None:
        try:
            import torch
            from transformers import AutoModelForCausalLM, AutoTokenizer
        except ImportError as exc:
            raise RuntimeError(
                "HuggingFace runner requires torch and transformers. Install them "
                "in the active environment before running scripts/run_tot_hf.py."
            ) from exc

        self.torch = torch
        self.AutoModelForCausalLM = AutoModelForCausalLM
        self.AutoTokenizer = AutoTokenizer
        self._models: dict[str, Any] = {}
        self._tokenizers: dict[str, Any] = {}
        self.last_text = ""
        if DEVICE == "cuda" and not torch.cuda.is_available():
            print("CUDA was requested but is not available; falling back to CPU.", flush=True)
            self.device = "cpu"
        else:
            self.device = DEVICE

    def unload_except(self, keep_model_id: str) -> None:
        if MEMORY_POLICY != "single_model":
            return
        removed = False
        for model_id in list(self._models):
            if model_id == keep_model_id:
                continue
            del self._models[model_id]
            del self._tokenizers[model_id]
            removed = True
        if removed:
            gc.collect()
            if self.torch.cuda.is_available():
                self.torch.cuda.empty_cache()

    def load(self, model_id: str) -> tuple[Any, Any]:
        self.unload_except(model_id)
        if model_id not in self._models:
            tokenizer = self.AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
            model_kwargs: dict[str, Any] = {
                "trust_remote_code": True,
            }
            if DEVICE_MAP is not None:
                model_kwargs["device_map"] = DEVICE_MAP
            if TORCH_DTYPE != "auto":
                model_kwargs["torch_dtype"] = getattr(self.torch, TORCH_DTYPE)
            else:
                model_kwargs["torch_dtype"] = "auto"
            model = self.AutoModelForCausalLM.from_pretrained(model_id, **model_kwargs)
            if DEVICE_MAP is None:
                model.to(self.device)
            self._tokenizers[model_id] = tokenizer
            self._models[model_id] = model
        return self._models[model_id], self._tokenizers[model_id]

    def chat(
        self,
        model_id: str,
        system: str,
        user: str,
        temperature: float,
        max_new_tokens: int,
    ) -> Any:
        model, tokenizer = self.load(model_id)
        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]
        prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        do_sample = temperature > 0
        generation_kwargs: dict[str, Any] = {
            "max_new_tokens": max_new_tokens,
            "do_sample": do_sample,
            "pad_token_id": tokenizer.eos_token_id,
        }
        if do_sample:
            generation_kwargs["temperature"] = temperature
            generation_kwargs["top_p"] = 0.9

        with self.torch.inference_mode():
            output_ids = model.generate(**inputs, **generation_kwargs)

        generated_ids = output_ids[0][inputs["input_ids"].shape[-1] :]
        text = tokenizer.decode(generated_ids, skip_special_tokens=True)
        self.last_text = text
        return extract_json(text)


def fill_template(template: str, replacements: dict[str, Any]) -> str:
    rendered = template
    for key, value in replacements.items():
        rendered = rendered.replace(
            "{" + key + "}",
            json.dumps(value, ensure_ascii=False, indent=2),
        )
    return rendered


def candidate_validation_errors(candidate: Any, min_chars: int) -> list[str]:
    if not isinstance(candidate, dict):
        return ["candidate is not a JSON object"]

    errors: list[str] = []
    allowed_keys = {"branch_id", "candidate_answer", "self_check_notes"}
    unexpected_keys = sorted(str(key) for key in candidate if key not in allowed_keys)
    if unexpected_keys:
        errors.append("unexpected top-level keys: " + ", ".join(unexpected_keys[:5]))

    if "branch_id" not in candidate:
        errors.append("missing branch_id")
    if "self_check_notes" not in candidate:
        errors.append("missing self_check_notes")

    answer = candidate.get("candidate_answer")
    if not isinstance(answer, str):
        errors.append("candidate_answer must be one plain string")
        answer_text = json.dumps(answer, ensure_ascii=False) if answer is not None else ""
    else:
        answer_text = answer.strip()

    if len(answer_text) < min_chars:
        errors.append(f"candidate_answer too short: {len(answer_text)} chars < {min_chars}")

    suspicious_keys = [
        str(key)
        for key in candidate
        if re.match(r"^-?\d|^-\d|^[-–]\d", str(key).strip())
    ]
    if suspicious_keys:
        errors.append("malformed outline keys detected: " + ", ".join(suspicious_keys[:5]))

    return errors


def build_retry_instruction(errors: list[str]) -> str:
    return (
        "\n\nThe previous draft was rejected by the local quality gate for these reasons:\n"
        + json.dumps(errors, ensure_ascii=False, indent=2)
        + "\nRegenerate the candidate from scratch. Follow the draft output contract exactly."
    )


def final_revision_validation_errors(final: Any, selected_candidate: Any) -> list[str]:
    if not isinstance(final, dict):
        return ["final revision is not a JSON object"]

    errors: list[str] = []
    final_answer = final.get("final_answer")
    if not isinstance(final_answer, str) or not final_answer.strip():
        errors.append("final_answer must be a non-empty string")
        final_answer_text = ""
    else:
        final_answer_text = final_answer.strip()

    candidate_answer = ""
    if isinstance(selected_candidate, dict):
        value = selected_candidate.get("candidate_answer")
        if isinstance(value, str):
            candidate_answer = value.strip()

    min_chars = int(len(candidate_answer) * MIN_FINAL_CANDIDATE_RATIO)
    if candidate_answer and len(final_answer_text) < min_chars:
        errors.append(
            "final_answer too short: "
            f"{len(final_answer_text)} chars < {min_chars} chars "
            f"({MIN_FINAL_CANDIDATE_RATIO:.0%} of selected candidate)"
        )

    if len(final_answer_text) <= 80:
        errors.append("final_answer looks like a title or summary, not a complete answer")

    revision_notes = final.get("revision_notes")
    if not isinstance(revision_notes, list) or not revision_notes:
        errors.append("revision_notes must list edits actually made")

    return errors


def build_final_retry_instruction(errors: list[str]) -> str:
    return (
        "\n\nThe previous final revision was rejected by the local quality gate for these reasons:\n"
        + json.dumps(errors, ensure_ascii=False, indent=2)
        + "\nRegenerate the final revision from scratch. The final_answer must be a complete "
        "revised answer, not a title, summary, or advice list."
    )


def same_branch_id(left: Any, right: Any) -> bool:
    return str(left) == str(right)


def find_by_branch_id(items: list[Any], branch_id: Any) -> Optional[Any]:
    for item in items:
        if isinstance(item, dict) and same_branch_id(item.get("branch_id") or item.get("id"), branch_id):
            return item
    return None


def final_revision_judgment(judgment: dict[str, Any]) -> dict[str, Any]:
    return {
        "scores_by_criterion": judgment.get("scores_by_criterion", []),
        "branch_fidelity": judgment.get("branch_fidelity", {}),
        "association_use": judgment.get("association_use", {}),
        "constraint_violations": judgment.get("constraint_violations", []),
        "top_fix": judgment.get("top_fix", ""),
    }


def build_judge_user(
    template: str,
    candidate: dict[str, Any],
    association_packet: dict[str, Any],
) -> str:
    return (
        fill_template(template, {"candidate_json": candidate})
        + "\n\nRAG mode and association packet used for this candidate:\n"
        + json.dumps(association_packet, ensure_ascii=False, indent=2)
        + ASSOCIATION_JUDGE_INSTRUCTIONS
    )


def run_record(
    record: dict[str, Any],
    client: HFChatClient,
    kb: list[dict[str, Any]],
) -> dict[str, Any]:
    if record.get("mode") != "staged":
        raise ValueError("run_tot_hf.py only supports staged request specs.")

    stages = record["stages"]
    print(f"  - map constraints for index={record.get('index')}", flush=True)
    constraint_map = client.chat(
        GENERATION_MODEL_ID,
        stages["constraint_map"]["system"],
        stages["constraint_map"]["user"],
        TEMPERATURE,
        MAX_NEW_TOKENS,
    )

    print(f"  - expand branches for index={record.get('index')}", flush=True)
    expand_user = fill_template(
        stages["expand_branches"]["user_template"],
        {"constraint_map_json": constraint_map},
    )
    branch_expansion = client.chat(
        GENERATION_MODEL_ID,
        stages["expand_branches"]["system"],
        expand_user,
        TEMPERATURE,
        MAX_NEW_TOKENS,
    )

    branches = branch_expansion.get("branches", [])
    if not isinstance(branches, list) or not branches:
        raise ValueError(f"No branches returned for index={record.get('index')}")

    selected_branches = branches[: int(record.get("branch_count", len(branches)))]
    progress = ProgressBar(
        total=2 + (3 * len(selected_branches)) + 2,
        label=f"index={record.get('index')}",
    )
    progress.update("constraint map complete")
    progress.update(f"expanded {len(branches)} branch plan(s)")

    query = str(record.get("query", ""))
    candidates: list[dict[str, Any]] = []
    judgments: list[dict[str, Any]] = []
    candidate_retry_notes: list[dict[str, Any]] = []
    branch_associations: list[dict[str, Any]] = []
    print(
        f"  - got {len(branches)} branch plan(s); drafting {len(selected_branches)}",
        flush=True,
    )
    for branch_no, branch in enumerate(selected_branches, 1):
        branch_id = branch.get("id", branch_no) if isinstance(branch, dict) else branch_no
        print(f"  - retrieve creative associations for branch {branch_id}", flush=True)
        association_packet = build_association_packet(
            query,
            constraint_map,
            branch,
            kb,
            RAG_TOP_K,
            RAG_MODE,
        )
        branch_associations.append(
            {"branch_id": branch_id, "association_packet": association_packet}
        )
        progress.update(f"branch {branch_id} association retrieval complete")

        print(f"  - draft branch {branch_id} ({branch_no}/{len(selected_branches)})", flush=True)
        draft_user = (
            fill_template(
                stages["draft_branch"]["user_template"],
                {
                    "constraint_map_json": constraint_map,
                    "branch_plan_json": branch,
                },
            )
            + (format_packet_for_prompt(association_packet) if RAG_MODE != "none" else "")
            + DRAFT_FORMAT_INSTRUCTIONS
        )
        candidate: Any = None
        errors: list[str] = []
        for attempt in range(CANDIDATE_RETRIES + 1):
            if attempt > 0:
                print(f"  - retry draft branch {branch_id} after validation failure", flush=True)
            try:
                candidate = client.chat(
                    GENERATION_MODEL_ID,
                    stages["draft_branch"]["system"],
                    draft_user if attempt == 0 else draft_user + build_retry_instruction(errors),
                    TEMPERATURE if attempt == 0 else min(TEMPERATURE, 0.3),
                    MAX_NEW_TOKENS,
                )
            except ValueError as exc:
                candidate = None
                errors = [f"draft did not return valid JSON: {exc}"]
                continue

            errors = candidate_validation_errors(candidate, MIN_CANDIDATE_CHARS)
            if not errors:
                break

        if errors:
            raise ValueError(
                f"Draft branch {branch_id} failed after {attempt + 1} attempt(s): {errors}"
            )
        candidate_retry_notes.append(
            {
                "branch_id": branch_id,
                "attempts": attempt + 1,
                "validation_errors": errors,
            }
        )
        candidates.append(candidate)
        progress.update(f"branch {branch_id} draft complete")

        print(f"  - judge branch {branch_id}", flush=True)
        judge_user = build_judge_user(
            stages["judge_branch"]["user_template"],
            candidate,
            association_packet,
        )
        judgment = client.chat(
            JUDGE_MODEL_ID,
            stages["judge_branch"]["system"],
            judge_user,
            JUDGE_TEMPERATURE,
            JUDGE_MAX_NEW_TOKENS,
        )
        judgments.append(judgment)
        progress.update(f"branch {branch_id} judgment complete")

    print("  - rerank candidates", flush=True)
    rerank_result = rerank(judgments)
    progress.update("programmatic rerank complete")
    selected_branch_id = rerank_result.get("selected_branch_id")
    selected_candidate = find_by_branch_id(candidates, selected_branch_id)
    selected_judgment = find_by_branch_id(judgments, selected_branch_id)
    selected_branch = find_by_branch_id(selected_branches, selected_branch_id)
    selected_association = find_by_branch_id(branch_associations, selected_branch_id)
    if selected_candidate is None or selected_judgment is None:
        raise ValueError(
            f"Could not resolve selected branch {selected_branch_id!r} for index={record.get('index')}"
        )

    selected_derived_metrics = derive_judgment_metrics(selected_judgment)
    final_revision_input = {
        "selected_candidate": selected_candidate,
        "selected_branch_plan": selected_branch,
        "selected_association_packet": (
            selected_association.get("association_packet")
            if isinstance(selected_association, dict)
            else None
        ),
        "selected_judgment": final_revision_judgment(selected_judgment),
        "derived_metrics": selected_derived_metrics,
    }

    print("  - revise selected candidate", flush=True)
    final_stage = stages["final_revision"]
    synth_user = (
        fill_template(
            final_stage["user_template"],
            {
                "constraint_map_json": constraint_map,
                "rerank_result_json": rerank_result,
                "final_revision_input_json": final_revision_input,
            },
        )
        + FINAL_REVISION_FORMAT_INSTRUCTIONS
    )
    final: Any = None
    final_errors: list[str] = []
    for attempt in range(FINAL_REVISION_RETRIES + 1):
        if attempt > 0:
            print("  - retry final revision after validation failure", flush=True)
        final = client.chat(
            GENERATION_MODEL_ID,
            final_stage["system"],
            synth_user if attempt == 0 else synth_user + build_final_retry_instruction(final_errors),
            TEMPERATURE if attempt == 0 else min(TEMPERATURE, 0.3),
            MAX_NEW_TOKENS,
        )
        final_errors = final_revision_validation_errors(final, selected_candidate)
        if not final_errors:
            break

    if final_errors:
        print(f"  - final revision kept with validation warnings: {final_errors}", flush=True)
    final_retry_notes = {
        "attempts": attempt + 1,
        "validation_errors": final_errors,
    }
    progress.update("final revision complete")

    return {
        "index": record.get("index"),
        "generation_model": GENERATION_MODEL_ID,
        "judge_model": JUDGE_MODEL_ID,
        "branch_count": record.get("branch_count"),
        "rag_mode": RAG_MODE,
        "branch_associations": branch_associations,
        "constraint_map": constraint_map,
        "branch_expansion": branch_expansion,
        "candidates": candidates,
        "judgments": judgments,
        "candidate_retry_notes": candidate_retry_notes,
        "rerank_result": rerank_result,
        "selected_branch": selected_branch,
        "selected_candidate": selected_candidate,
        "selected_association": selected_association,
        "selected_judgment": selected_judgment,
        "selected_derived_metrics": selected_derived_metrics,
        "final_revision_input": final_revision_input,
        "final_retry_notes": final_retry_notes,
        "final": final,
    }


def append_jsonl(path: Path, item: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(item, ensure_ascii=False) + "\n")


def latest_request_path() -> Path:
    request_paths = sorted(
        RUNS_DIR.glob("*_request_*.jsonl"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    if not request_paths:
        raise FileNotFoundError(
            f"No *_request_*.jsonl files found in {RUNS_DIR}. Run build_tot_requests.py first."
        )
    return request_paths[0]


def output_path_for(records: list[dict[str, Any]]) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    if len(records) == 1:
        index = records[0].get("index", "unknown")
        return RUNS_DIR / f"{index}_hf_{RAG_MODE}_output_{timestamp}.jsonl"
    return RUNS_DIR / f"batch_hf_{RAG_MODE}_output_{timestamp}.jsonl"


def main() -> None:
    input_path = REQUEST_PATH or latest_request_path()
    records = load_jsonl(input_path)
    output_path = output_path_for(records)
    kb = load_kb()
    client = HFChatClient()

    for i, record in enumerate(records, 1):
        print(
            f"[{i}/{len(records)}] index={record.get('index')} "
            f"generation_model={GENERATION_MODEL_ID} judge_model={JUDGE_MODEL_ID} "
            f"rag_mode={RAG_MODE}"
        )
        result = run_record(record, client, kb)
        append_jsonl(output_path, result)

    print(f"Read staged ToT request(s) from: {input_path}")
    print(f"Wrote {len(records)} HF RAG ToT output(s) to: {output_path}")


if __name__ == "__main__":
    main()
