"""Run staged Tree-of-Thought requests with a local Ollama model.

Edit the global configuration block below when you want to change models,
Ollama settings, or candidate validation thresholds. By default, the runner uses
the newest ``*_request_*.jsonl`` file under data/runs/ and writes an output file
named ``{index}_output_{timestamp}.jsonl``.
"""

import json
import re
import urllib.error
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from rerank_tot_candidats import derive_judgment_metrics, rerank


ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = ROOT / "data" / "runs"

# Set REQUEST_PATH to a concrete Path to run a specific request file. Leave it as
# None to run the newest timestamped request generated by build_tot_requests.py.
REQUEST_PATH: Optional[Path] = None

GENERATION_MODEL = "llama3.1:8b"
JUDGE_MODEL = "qwen2.5:14b-instruct-q4_K_M"
OLLAMA_URL = "http://localhost:11434/api/chat"
TEMPERATURE = 0.7
JUDGE_TEMPERATURE = 0.0
NUM_CTX = 8192
TIMEOUT = 600
CANDIDATE_RETRIES = 2
MIN_CANDIDATE_CHARS = 600
FINAL_REVISION_RETRIES = 1
MIN_FINAL_CANDIDATE_RATIO = 0.7

HF_TO_OLLAMA_MODEL = {
    "meta-llama/Meta-Llama-3.1-8B-Instruct": GENERATION_MODEL,
}
DRAFT_FORMAT_INSTRUCTIONS = """

Draft output contract:
Return exactly one valid JSON object with these top-level keys only:
{
  "branch_id": "same id as the branch plan",
  "candidate_answer": "a complete, directly usable answer as one plain string",
  "self_check_notes": ["short note about constraints covered"]
}
Do not put outline headings or act numbers as JSON keys. Put the whole answer,
including headings and bullets if useful, inside candidate_answer as text.
The JSON must be valid: escape line breaks inside candidate_answer as needed; do
not emit an unterminated string or raw multiline JSON string.
The candidate_answer must be complete enough for judging, not a stub.
"""
FINAL_REVISION_FORMAT_INSTRUCTIONS = """

Final revision output contract:
The final_answer must contain a complete revised plot design, not just a title.
It must be at least as detailed as selected_candidate.candidate_answer.
Do not shorten the selected candidate.
Do not output only the title.
Do not merely list suggestions.
Apply the selected judgment feedback directly inside final_answer.
revision_notes must describe edits actually made.
"""


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as fh:
        for line_no, raw in enumerate(fh, 1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                records.append(json.loads(raw))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {line_no} of {path}") from exc
    return records


def resolve_generation_model(request_model: Optional[str]) -> str:
    if GENERATION_MODEL:
        return GENERATION_MODEL
    if request_model in HF_TO_OLLAMA_MODEL:
        return HF_TO_OLLAMA_MODEL[request_model]
    return request_model or "llama3.1:8b"


def extract_json(text: str) -> Any:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r"(\{.*\}|\[.*\])", text, flags=re.DOTALL)
    if not match:
        raise ValueError(f"Model did not return JSON: {text[:500]}")
    return json.loads(match.group(1))


def ollama_chat(
    url: str,
    model: str,
    system: str,
    user: str,
    temperature: float,
    num_ctx: int,
    timeout: int,
) -> Any:
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "stream": False,
        "format": "json",
        "options": {
            "temperature": temperature,
            "num_ctx": num_ctx,
        },
    }
    data = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            raw = response.read().decode("utf-8")
    except urllib.error.URLError as exc:
        raise RuntimeError(
            "Could not reach Ollama. Start it and pull the model first:\n"
            "  ollama pull llama3.1:8b\n"
            "  ollama serve"
        ) from exc

    body = json.loads(raw)
    content = body.get("message", {}).get("content", "")
    return extract_json(content)


def fill_template(template: str, replacements: dict[str, Any]) -> str:
    rendered = template
    for key, value in replacements.items():
        rendered = rendered.replace(
            "{" + key + "}",
            json.dumps(value, ensure_ascii=False, indent=2),
        )
    return rendered


def candidate_validation_errors(candidate: Any, min_chars: int) -> list[str]:
    if not isinstance(candidate, dict):
        return ["candidate is not a JSON object"]

    errors: list[str] = []
    allowed_keys = {"branch_id", "candidate_answer", "self_check_notes"}
    unexpected_keys = sorted(str(key) for key in candidate if key not in allowed_keys)
    if unexpected_keys:
        errors.append(
            "unexpected top-level keys: " + ", ".join(unexpected_keys[:5])
        )

    if "branch_id" not in candidate:
        errors.append("missing branch_id")
    if "self_check_notes" not in candidate:
        errors.append("missing self_check_notes")

    answer = candidate.get("candidate_answer")
    if not isinstance(answer, str):
        errors.append("candidate_answer must be one plain string")
        answer_text = json.dumps(answer, ensure_ascii=False) if answer is not None else ""
    else:
        answer_text = answer.strip()

    if len(answer_text) < min_chars:
        errors.append(
            f"candidate_answer too short: {len(answer_text)} chars < {min_chars}"
        )

    suspicious_keys = [
        str(key)
        for key in candidate
        if re.match(r"^-?\d|^-\d|^[-–]\d", str(key).strip())
    ]
    if suspicious_keys:
        errors.append(
            "malformed outline keys detected: " + ", ".join(suspicious_keys[:5])
        )

    return errors


def build_retry_instruction(errors: list[str]) -> str:
    return (
        "\n\nThe previous draft was rejected by the local quality gate for these reasons:\n"
        + json.dumps(errors, ensure_ascii=False, indent=2)
        + "\nRegenerate the candidate from scratch. Follow the draft output contract exactly."
    )


def final_revision_validation_errors(final: Any, selected_candidate: Any) -> list[str]:
    if not isinstance(final, dict):
        return ["final revision is not a JSON object"]

    errors: list[str] = []
    final_answer = final.get("final_answer")
    if not isinstance(final_answer, str) or not final_answer.strip():
        errors.append("final_answer must be a non-empty string")
        final_answer_text = ""
    else:
        final_answer_text = final_answer.strip()

    candidate_answer = ""
    if isinstance(selected_candidate, dict):
        value = selected_candidate.get("candidate_answer")
        if isinstance(value, str):
            candidate_answer = value.strip()

    min_chars = int(len(candidate_answer) * MIN_FINAL_CANDIDATE_RATIO)
    if candidate_answer and len(final_answer_text) < min_chars:
        errors.append(
            "final_answer too short: "
            f"{len(final_answer_text)} chars < {min_chars} chars "
            f"({MIN_FINAL_CANDIDATE_RATIO:.0%} of selected candidate)"
        )

    if len(final_answer_text) <= 80:
        errors.append("final_answer looks like a title or summary, not a complete answer")

    revision_notes = final.get("revision_notes")
    if not isinstance(revision_notes, list) or not revision_notes:
        errors.append("revision_notes must list edits actually made")

    return errors


def build_final_retry_instruction(errors: list[str]) -> str:
    return (
        "\n\nThe previous final revision was rejected by the local quality gate for these reasons:\n"
        + json.dumps(errors, ensure_ascii=False, indent=2)
        + "\nRegenerate the final revision from scratch. The final_answer must be a complete "
        "revised answer, not a title, summary, or advice list."
    )


def same_branch_id(left: Any, right: Any) -> bool:
    return str(left) == str(right)


def find_by_branch_id(items: list[Any], branch_id: Any) -> Optional[Any]:
    for item in items:
        if isinstance(item, dict) and same_branch_id(item.get("branch_id") or item.get("id"), branch_id):
            return item
    return None


def final_revision_judgment(judgment: dict[str, Any]) -> dict[str, Any]:
    return {
        "scores_by_criterion": judgment.get("scores_by_criterion", []),
        "branch_fidelity": judgment.get("branch_fidelity", {}),
        "constraint_violations": judgment.get("constraint_violations", []),
        "top_fix": judgment.get("top_fix", ""),
    }


def run_record(
    record: dict[str, Any],
    generation_model: str,
    judge_model: str,
    ollama_url: str,
    temperature: float,
    judge_temperature: float,
    num_ctx: int,
    timeout: int,
    candidate_retries: int,
    min_candidate_chars: int,
) -> dict[str, Any]:
    if record.get("mode") != "staged":
        raise ValueError("run_tot_ollama.py only supports staged request specs.")

    stages = record["stages"]
    print(f"  - map constraints for index={record.get('index')}", flush=True)
    constraint_map = ollama_chat(
        ollama_url,
        generation_model,
        stages["constraint_map"]["system"],
        stages["constraint_map"]["user"],
        temperature,
        num_ctx,
        timeout,
    )

    print(f"  - expand branches for index={record.get('index')}", flush=True)
    expand_user = fill_template(
        stages["expand_branches"]["user_template"],
        {"constraint_map_json": constraint_map},
    )
    branch_expansion = ollama_chat(
        ollama_url,
        generation_model,
        stages["expand_branches"]["system"],
        expand_user,
        temperature,
        num_ctx,
        timeout,
    )

    branches = branch_expansion.get("branches", [])
    if not isinstance(branches, list) or not branches:
        raise ValueError(f"No branches returned for index={record.get('index')}")

    candidates: list[dict[str, Any]] = []
    judgments: list[dict[str, Any]] = []
    candidate_retry_notes: list[dict[str, Any]] = []
    selected_branches = branches[: int(record.get("branch_count", len(branches)))]
    print(
        f"  - got {len(branches)} branch plan(s); drafting {len(selected_branches)}",
        flush=True,
    )
    for branch_no, branch in enumerate(selected_branches, 1):
        branch_id = branch.get("id", branch_no) if isinstance(branch, dict) else branch_no
        print(
            f"  - draft branch {branch_id} ({branch_no}/{len(selected_branches)})",
            flush=True,
        )
        draft_user = (
            fill_template(
                stages["draft_branch"]["user_template"],
                {
                    "constraint_map_json": constraint_map,
                    "branch_plan_json": branch,
                },
            )
            + DRAFT_FORMAT_INSTRUCTIONS
        )
        candidate: Any = None
        errors: list[str] = []
        for attempt in range(candidate_retries + 1):
            if attempt > 0:
                print(
                    f"  - retry draft branch {branch_id} after validation failure",
                    flush=True,
                )
            try:
                candidate = ollama_chat(
                    ollama_url,
                    generation_model,
                    stages["draft_branch"]["system"],
                    draft_user if attempt == 0 else draft_user + build_retry_instruction(errors),
                    temperature if attempt == 0 else min(temperature, 0.3),
                    num_ctx,
                    timeout,
                )
            except ValueError as exc:
                candidate = None
                errors = [f"draft did not return valid JSON: {exc}"]
                continue

            errors = candidate_validation_errors(candidate, min_candidate_chars)
            if not errors:
                break

        if errors:
            raise ValueError(
                f"Draft branch {branch_id} failed after {attempt + 1} attempt(s): {errors}"
            )
        candidate_retry_notes.append(
            {
                "branch_id": branch_id,
                "attempts": attempt + 1,
                "validation_errors": errors,
            }
        )
        candidates.append(candidate)

        print(f"  - judge branch {branch_id}", flush=True)
        judge_user = fill_template(
            stages["judge_branch"]["user_template"],
            {"candidate_json": candidate},
        )
        judgment = ollama_chat(
            ollama_url,
            judge_model,
            stages["judge_branch"]["system"],
            judge_user,
            judge_temperature,
            num_ctx,
            timeout,
        )
        judgments.append(judgment)

    print("  - rerank candidates", flush=True)
    rerank_result = rerank(judgments)
    selected_branch_id = rerank_result.get("selected_branch_id")
    selected_candidate = find_by_branch_id(candidates, selected_branch_id)
    selected_judgment = find_by_branch_id(judgments, selected_branch_id)
    selected_branch = find_by_branch_id(selected_branches, selected_branch_id)
    if selected_candidate is None or selected_judgment is None:
        raise ValueError(
            f"Could not resolve selected branch {selected_branch_id!r} for index={record.get('index')}"
        )

    selected_derived_metrics = derive_judgment_metrics(selected_judgment)
    final_revision_input = {
        "selected_candidate": selected_candidate,
        "selected_branch_plan": selected_branch,
        "selected_judgment": final_revision_judgment(selected_judgment),
        "derived_metrics": selected_derived_metrics,
    }

    print("  - revise selected candidate", flush=True)
    final_stage = stages["final_revision"]
    synth_user = (
        fill_template(
            final_stage["user_template"],
            {
                "constraint_map_json": constraint_map,
                "rerank_result_json": rerank_result,
                "final_revision_input_json": final_revision_input,
            },
        )
        + FINAL_REVISION_FORMAT_INSTRUCTIONS
    )
    final: Any = None
    final_errors: list[str] = []
    for attempt in range(FINAL_REVISION_RETRIES + 1):
        if attempt > 0:
            print("  - retry final revision after validation failure", flush=True)
        final = ollama_chat(
            ollama_url,
            generation_model,
            final_stage["system"],
            synth_user if attempt == 0 else synth_user + build_final_retry_instruction(final_errors),
            temperature if attempt == 0 else min(temperature, 0.3),
            num_ctx,
            timeout,
        )
        final_errors = final_revision_validation_errors(final, selected_candidate)
        if not final_errors:
            break

    if final_errors:
        print(
            f"  - final revision kept with validation warnings: {final_errors}",
            flush=True,
        )
    final_retry_notes = {
        "attempts": attempt + 1,
        "validation_errors": final_errors,
    }

    return {
        "index": record.get("index"),
        "generation_model": generation_model,
        "judge_model": judge_model,
        "branch_count": record.get("branch_count"),
        "constraint_map": constraint_map,
        "branch_expansion": branch_expansion,
        "candidates": candidates,
        "judgments": judgments,
        "candidate_retry_notes": candidate_retry_notes,
        "rerank_result": rerank_result,
        "selected_branch": selected_branch,
        "selected_candidate": selected_candidate,
        "selected_judgment": selected_judgment,
        "selected_derived_metrics": selected_derived_metrics,
        "final_revision_input": final_revision_input,
        "final_retry_notes": final_retry_notes,
        "final": final,
    }


def append_jsonl(path: Path, item: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(item, ensure_ascii=False) + "\n")


def latest_request_path() -> Path:
    request_paths = sorted(
        RUNS_DIR.glob("*_request_*.jsonl"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    if not request_paths:
        raise FileNotFoundError(
            f"No *_request_*.jsonl files found in {RUNS_DIR}. Run build_tot_requests.py first."
        )
    return request_paths[0]


def output_path_for(records: list[dict[str, Any]]) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    if len(records) == 1:
        index = records[0].get("index", "unknown")
        return RUNS_DIR / f"{index}_output_{timestamp}.jsonl"
    return RUNS_DIR / f"batch_output_{timestamp}.jsonl"


def main() -> None:
    input_path = REQUEST_PATH or latest_request_path()
    records = load_jsonl(input_path)
    output_path = output_path_for(records)

    for i, record in enumerate(records, 1):
        generation_model = resolve_generation_model(record.get("model"))
        print(
            f"[{i}/{len(records)}] index={record.get('index')} "
            f"generation_model={generation_model} judge_model={JUDGE_MODEL}"
        )
        result = run_record(
            record,
            generation_model,
            JUDGE_MODEL,
            OLLAMA_URL,
            TEMPERATURE,
            JUDGE_TEMPERATURE,
            NUM_CTX,
            TIMEOUT,
            CANDIDATE_RETRIES,
            MIN_CANDIDATE_CHARS,
        )
        append_jsonl(output_path, result)

    print(f"Read staged ToT request(s) from: {input_path}")
    print(f"Wrote {len(records)} staged ToT output(s) to: {output_path}")


if __name__ == "__main__":
    main()
